# Generated by Django 5.2.6 on 2025-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ENGINEER', 'Инженер'), ('MANAGER', 'Менеджер'), ('OBSERVATOR', 'Наблюдатель')], default='OBSERVATOR', max_length=20),
        ),
    ]
